### ISSUE TITLE
undefined reference usbd_***

### ISSUE THREAD

**Issue by nickfox-taterli** [sipeed/platform-gd32v#14]
The same code is working well with Eclipse, can't work with Platform IO?

I checked and it includes all the needed files, but it just didn't work under Platform IO.

Project:https://drive.google.com/file/d/1PBh_j7_V_jaYRxJ7P_ZWM_cE_keZ4Msz/view?usp=sharing

`c:/users/taterli/.platformio/packages/toolchain-gd32v/bin/../lib/gcc/riscv-nuclei-elf/9.2.0/../../../../riscv-nuclei-elf/bin/ld.exe: .pio\build\sipeed-longan-nano\src\standard_hid_core.o: in function `hid_deinit':
standard_hid_core.c:(.text.hid_deinit+0x8): undefined reference to `usbd_ep_clear'
c:/users/taterli/.platformio/packages/toolchain-gd32v/bin/../lib/gcc/riscv-nuclei-elf/9.2.0/../../../../riscv-nuclei-elf/bin/ld.exe: .pio\build\sipeed-longan-nano\src\standard_hid_core.o: in function `hid_init':
standard_hid_core.c:(.text.hid_init+0xc): undefined reference to `usbd_ep_setup'
c:/users/taterli/.platformio/packages/toolchain-gd32v/bin/../lib/gcc/riscv-nuclei-elf/9.2.0/../../../../riscv-nuclei-elf/bin/ld.exe: .pio\build\sipeed-longan-nano\src\main.o: in function `main':
main.c:(.text.startup.main+0x24): undefined reference to `usbd_init'
c:/users/taterli/.platformio/packages/toolchain-gd32v/bin/../lib/gcc/riscv-nuclei-elf/9.2.0/../../../../riscv-nuclei-elf/bin/ld.exe: .pio\build\sipeed-longan-nano\src\gd32vf103_it.o: in function `USBFS_IRQHandler':
gd32vf103_it.c:(.text.USBFS_IRQHandler+0x8): undefined reference to `usbd_isr'
c:/users/taterli/.platformio/packages/toolchain-gd32v/bin/../lib/gcc/riscv-nuclei-elf/9.2.0/../../../../riscv-nuclei-elf/bin/ld.exe: .pio\build\sipeed-longan-nano\src\gd32vf103_it.o: in function `USBFS_WKUP_IRQHandler':
gd32vf103_it.c:(.text.USBFS_WKUP_IRQHandler+0x2a): undefined reference to `usb_clock_active'`

**Comment by Phil242** [comment]
Hi,

Problem is first coming from the fact the SDK doesn't compile the USB files of the middle-ware, because the part of the code is commented ! See in file : [https://github.com/sipeed/platform-gd32v/blob/master/builder/frameworks/firmware_library.py](https://github.com/sipeed/platform-gd32v/blob/master/builder/frameworks/firmware_library.py)

The commented code : 
`libs = [
    env.BuildLibrary(
        join("$BUILD_DIR", "standard_peripheral"),
        join(FRAMEWORK_DIR, "GD32VF103_standard_peripheral")),

# #    env.BuildLibrary(
# #        join("$BUILD_DIR", "usbfs_driver"),
# #        join(FRAMEWORK_DIR, "GD32VF103_usbfs_driver")),
    
    env.BuildLibrary(
        join("$BUILD_DIR", "RISCV"),
        join(FRAMEWORK_DIR, "RISCV")),

]`

I think the problem start from here.

Cheers,

**Comment by nickfox-taterli** [comment]
`C:\Users\TaterLi\.platformio\packages\framework-gd32vf103-sdk\GD32VF103_usbfs_driver\Source\drv_usb_core.c:251:20: error: '__packed' undeclared (first use in this function)
  251 |         *fifo = *((__packed uint32_t *)src_buf);
      |                    ^~~~~~~~
C:\Users\TaterLi\.platformio\packages\framework-gd32vf103-sdk\GD32VF103_usbfs_driver\Source\drv_usb_core.c:251:20: note: each undeclared identifier is reported only once for each function it appears in
C:\Users\TaterLi\.platformio\packages\framework-gd32vf103-sdk\GD32VF103_usbfs_driver\Source\drv_usb_core.c:251:28: error: expected ')' before 'uint32_t'
  251 |         *fifo = *((__packed uint32_t *)src_buf);
      |                   ~        ^~~~~~~~~
      |                            )
C:\Users\TaterLi\.platformio\packages\framework-gd32vf103-sdk\GD32VF103_usbfs_driver\Source\drv_usb_core.c:251:40: error: expected ')' before 'src_buf'        
  251 |         *fifo = *((__packed uint32_t *)src_buf);
      |                  ~                     ^~~~~~~
      |                                        )
C:\Users\TaterLi\.platformio\packages\framework-gd32vf103-sdk\GD32VF103_usbfs_driver\Source\drv_usb_core.c: In function 'usb_rxfifo_read':
C:\Users\TaterLi\.platformio\packages\framework-gd32vf103-sdk\GD32VF103_usbfs_driver\Source\drv_usb_core.c:274:11: error: '__packed' undeclared (first use in this function)
  274 |         *(__packed uint32_t *)dest_buf = *fifo;
      |           ^~~~~~~~
C:\Users\TaterLi\.platformio\packages\framework-gd32vf103-sdk\GD32VF103_usbfs_driver\Source\drv_usb_core.c:274:19: error: expected ')' before 'uint32_t'
  274 |         *(__packed uint32_t *)dest_buf = *fifo;
      |          ~        ^~~~~~~~~
      |                   )
C:\Users\TaterLi\.platformio\packages\framework-gd32vf103-sdk\GD32VF103_usbfs_driver\Source\drv_usb_core.c:274:31: error: expected ';' before 'dest_buf'       
  274 |         *(__packed uint32_t *)dest_buf = *fifo;
      |                               ^~~~~~~~
      |                               ;`

Copy GD32VF103_Firmware_Library App code and uncomment firmware_library.py and recompile.

It looks like some definitions(or code) are not compatible,delete all **__packed** attr,

I found that many macro undefine,such as USB_HTX_NPFIFO_FS_SIZE

**Comment by nickfox-taterli** [comment]
I think I should check it out later or try to port the incompatible part myself.

**Comment by Phil242** [comment]
Sorry, I'm lost: why did you close the issue ? Nothing is solved.

**Comment by orzel** [comment]
I confirm, i have the same problem, probably the same reason... This ticket is not fixed.
